### ISSUE TITLE
Can't import duffel components

### ISSUE THREAD

**Issue by Rytis-t** [duffelhq/duffel-components#156]
**Describe the bug**

When importing 
`import { DuffelPayments, DuffelAncillaries } from '@duffel/components`
and using components
```
<DuffelPayments paymentIntentClientToken="eyJjbGllbnRfc2VjcmV0IjoicGlfM0psczlVQWcySmhFeTh2WTBSTm1MU0JkX3NlY3JldF9QUW9yZXNuU3laeWJadGRiejZwNzBCbUdPIiwicHVibGlzaGFibGVfa2V5IjoicGtfdGVzdF9EQUJLY0E2Vzh6OTc0cTdPSWY0YmJ2MVQwMEpwRmMyOUpWIn0="
      onSuccessfulPayment={console.log}
      onFailedPayment={console.log}
    />
```

 react/nextjs throws an error: 

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

(Same with DuffelAncillaries or DuffelPayments).

Library version: **3.1.2 (if I downgrade to 2.7.20, CardPayment (Which is same as DuffelPayments as far as I can tell) actually works as intended, however 2.7.20 does not have Ancillaries so we can't just use that version.)** I'm installing it: **npm i @duffel/components**. Framework I'm using is **NextJS**.

Code sample: https://codesandbox.io/p/sandbox/github/Rytis-t/duffelcomponents/tree/main

EDIT: Also, if I let's say import and log:

```
import { destroyCookie } from 'nookies';
import { DuffelPayments } from '@duffel/components';

console.log(destroyCookie)
console.log(DuffelPayments)
```

any other imported function is logged as: 
`function destroyCookie(ctx, name, options)`

but DuffelPayments is _undefined_.

**Comment by andrejak** [comment]
Hi! As a temporary fix, could you try using version 3.0.0? That seemed to work for me in the CodeSandbox example, let me know if it doesn't work in your project. In the meantime, I'll try to figure out what has gone wrong in the latest version.

**Comment by lluchkaa** [comment]
I can confirm that is happening in my current project too

**Comment by andrejak** [comment]
Could you let me know if using 3.1.3 works for you?

**Comment by karadenizemirr** [comment]
Explain problem: Could not find a declaration file for module '@duffel/components'. '/Users/karadenizemirr/Desktop/Projects/duffel_app/node_modules/@duffel/components/react-dist/index.js' implicitly has an 'any' type. 

Try `npm i --save-dev @types/duffel__components` if it exists or add a new declaration (.d.ts) file containing `declare module '@duffel/components

style not found

**Comment by Rytis-t** [comment]
> Could you let me know if using 3.1.3 works for you?

It is working with the 3.1.3 version, Thank you! 

The only thing now is that IDE is tripping after this update, saying:
`Could not find a declaration file for module @duffel/components `

That's not limited to DuffelPayments or DuffelAncillaries, I've had previously imported "Offer" type which doesn't work right now.

**Comment by Rytis-t** [comment]
Also few minor things:

Whenever ancillaries component loads, it calls:

https://assets.duffel.com/components/3.1.3/global.css - 3.1.3 global.css does not exist, 3.1.2 does though, so I imagine this is a simple fix. 

However, when I call ancillaries component like so:
```
<DuffelAncillaries
        debug={true}
        offer_id='off_0000Ab9nrNAm3lwqfAGP2g'
        client_key='SFMyNTY.g2gDdAAAAANkAAlsaXZlX21vZGVkAAVmYWxzZWQAD29yZ2FuaXNhdGlvbl9pZG0AAAAab3JnXzAwMDBBWWE2bnJXMnkyVHBLbDBIWEVkAAtyZXNvdXJjZV9pZG0AAAAab3JxXzAwMDBBYjluck12QXpsVEhzbXh3akFuBgD-wDdriwFiAAFRgA.L8-Mv7QWih9iPHPxtA3ZBMi0HkrB3PhPYIC9QVAvKys'
        services={["bags", "seats", "cancel_for_any_reason"]}
        passengers={[
            {
            given_name: "test",
            family_name: "test",
            type: "adult",
            title: "dr",
            phone_number: "+442080160509",
            gender: "m",
            email: "mail@mail.com",
            born_on: "1987-07-24",
            id: "pas_0000Ab9nrMvAzlTHsmxwjC"
            }
        ]}
        onPayloadReady={console.log}
    />
```

it returns an error: 

> Failed to load extras
> r is null

In network tab, I can see that calls for offer and seat maps are being made and they actually return correct information it seems, however in Ancillaries debug console, I see this: 
![image](https://github.com/duffelhq/duffel-components/assets/129058873/e121013b-c8f0-4e7e-ae56-b1e275375b1b)
offer is undefined for some reason, again, even though in network tab I can see that offer is being returned from duffel API. Not sure if this is something with NPM package or is this a mistake on my end, perhaps you can comment? Thanks.

**Comment by andrejak** [comment]
Thank you for reporting, we will look into these in the next few days!

**Comment by lluchkaa** [comment]
@andrejak I see that right now `DuffelAncillaries` component can't load styles as there are no styles under `https://assets.duffel.com/components/3.1.3/global.css`. But there are styles on previous version `https://assets.duffel.com/components/3.1.2/global.css`

**Comment by lluchkaa** [comment]
@Rytis-t I managed to fix types error with a module declaration:
```tsx
declare module '@duffel/components' {
  export * from '@duffel/components/src/index'
}
```

**Comment by Rytis-t** [comment]
@lluchkaa 

Thanks. Does the Ancillaries module itself work for you? (Trying to figure out if getting

> Failed to load extras
> r is null

something on my end or is this a problem with the package.) Thanks.

**Comment by lluchkaa** [comment]
@Rytis-t do you use partial offers? Because Duffel Ancillaries right now do not support it.
I previously also faced a similar issue, then I contacted support and right now the only way to use Duffel Ancillaries with partial offers is to pass the whole `offer` + `seat_maps` to the component (you should load both `offer` and `seat_maps` using API)

**Comment by Rytis-t** [comment]
> @Rytis-t do you use partial offers? Because Duffel Ancillaries right now do not support it. I previously also faced a similar issue, then I contacted support and right now the only way to use Duffel Ancillaries with partial offers is to pass the whole `offer` + `seat_maps` to the component (you should load both `offer` and `seat_maps` using API)

I'm not using partial offers. I guess I'll try to supply seat_maps manually, see if that helps. Thanks.

**Comment by andrejak** [comment]
Hi, https://assets.duffel.com/components/3.1.3/global.css should now be up, sorry about that. Will look into the other issues.
