### ISSUE TITLE
On DuffelAncilliaries wrong display of Seats and all unavailable

### ISSUE THREAD

**Issue by Ruben35** [duffelhq/duffel-components#214]
### Describe the bug
When selecting seats for some airlines (in this example specific **American Airlines**) on a roundtrip **MEX-CDG** or **MEX-LAS** there is an odd accomodation of the ammenities. Also **all the seats on all the slices appears as unavailable**.

### Version of @duffel/components

1. **Version:** `"@duffel/components": "^3.1.5"`, so in yarn lock we are using `"3.4.3"`
2. **Installation:** YARN
3. **Framework:** Next.js

### Code sample to reproduce
The Duffel Component is rendered as in the documentation (the option of providing an `offer`, `passengers` and  a `client_key`) like this:
```jsx
<DuffelAncillaries
  styles={{
    buttonCornerRadius: '5px',
    accentColor: color,
    fontFamily: 'inherit',
  }}
  offer={props.offer }
  client_key={props.clientKey}
  passengers={passengers}
  services={['bags', 'seats', 'cancel_for_any_reason']}
  onPayloadReady={handleOnPaylodReady}
/>
```
The DuffelAncilliaires component makes the petition for the `seat_maps` and I can see that it has information there.
- The request id for this petition of seat maps for MEX-CDG is `F61x4npiei_YFs0A1bND`. 
- The request id for this petition of seat maps for MEX-LAS is `F62_XEw2UxbT8YEA588h`. 

### Expected behavior
Not sure if the amennities should look like that but, if seat maps are retrieved at least few seats should be available (no make sense that on any slice there is none selectable seat)

And if not, there should be an advertisment like "No Available" on the button before selecting the seats.

### Screenshots

Here is how it looks on my frontend:
![Captura de pantalla 2024-01-24 192249](https://github.com/duffelhq/duffel-components/assets/30848819/80d9b8e6-5efb-4e10-a4f5-7b909379ff2a)
![Captura de pantalla 2024-01-24 192546](https://github.com/duffelhq/duffel-components/assets/30848819/0373a8fe-8e4c-4cff-9134-812457f6e209)

### Additional context
Don't know if it is a specific problem for this airline or is something general, also I see that this problem happen also in Duffel Dashboard (when creating an order there).

**Comment by igorp1** [comment]
Hi again @Ruben35, from the [latest release (3.5.2)](https://github.com/duffelhq/duffel-components/releases/tag/v3.5.2) we'll disable the card if no seats are available.

**Comment by Ruben35** [comment]
Thank you so much ✨
