### ISSUE TITLE
Error while trying duffel payments example

### ISSUE THREAD

**Issue by devilevil100** [duffelhq/duffel-components#267]
POST https://api.stripe.com/v1/payment_intents/pi_3Jls9UAg2JhEy8vY0RNmLSBd/confirm 400 (Bad Request)

{type: 'invalid_request_error', code: 'payment_intent_unexpected_state', doc_url: 'https://stripe.com/docs/error-codes/payment-intent-unexpected-state', message: 'A processing error occurred.', payment_intent: {…}, …}
code
: 
"payment_intent_unexpected_state"
doc_url
: 
"https://stripe.com/docs/error-codes/payment-intent-unexpected-state"
message
: 
"A processing error occurred."

**Comment by igorp1** [comment]
@devilevil100, seems like you are reaching out to stripe, which won't work with our payment component. You can learn more about it [on this guide](https://duffel.com/guides/collecting-payments-from-your-customers). But with that said, we have deprecated that product, you won't find much documentation or the API reference for it around. Please reach out to help@duffel.com if this is important to you and they'll give you some direction on whether that's possible or alternatives.
