### ISSUE TITLE
Duffel Payment - CSP(Content Security Policy) Error Blocking 3D Secure 2 Authentication Modal

### ISSUE THREAD

**Issue by Danish-idigitalxp** [duffelhq/duffel-components#297]
**Describe the bug**
We were testing the card numbers for the Duffel Payment Component from this document:
"https://duffel.com/docs/api/overview/test-mode/test-card-numbers"

In this document, there is one card for 3D Secure 2 authentication (4000 0000 0000 3220). When we tried using that card and once the payment_intents was confirmed, we got this error:
' Refused to load the image 'data/png;base64,iVBORw0KGgo=' because it violates the following Content Security Policy directive: "img-src 'self'". '

We did some research and tried those solutions. Additionally, we tried fixing this by adding that directive to our Content Security Policy, but the error persists. However, because of this error, the content inside the 3D Secure 2 authentication modal is not visible to the user.

**Version of @duffel/components**
Please add:

1. "@duffel/components": "^3.7.7"
2. We are using npm to install
3. We are using the React framework

**Expected behavior**
The content inside the 3D Secure 2 authentication modal should be visible to the user.

**Screenshots**
![3DS  Content Security Policy error](https://github.com/duffelhq/duffel-components/assets/92710316/df052ed4-ed1f-49eb-b2c2-cfc80380dbc3)
![Duffel payment confirm response](https://github.com/duffelhq/duffel-components/assets/92710316/a2cb4b8b-0dcc-4e4d-895f-58de5c88f9d3)

**Comment by andrejak** [comment]
Hi, thank you for reporting. To help us prioritise, can you just confirm you've got access to live mode already, as we are currently not accepting new customers on to Duffel Payments?

**Comment by Danish-idigitalxp** [comment]
Hi,

Yes, we already have access to live mode. We are using Duffel Payments for the Duffel Flights API, which is also currently live.

**Comment by igorp1** [comment]
Hi @Danish-idigitalxp, the Duffel payments component you see is [implemented here](https://github.com/duffelhq/duffel-components/blob/main/src/components/DuffelPayments/DuffelPayments.tsx). We don't make any requests or serve any content, the component is just a bit of javascript. Please, look in your application's where CSP headers may be set. 

If the issue still persists and you find we can help, please reopen this and share a code sandbox please so I can understand more about how the component is being used.
