### ISSUE TITLE
Why are reusable components contain Duffe's Sentry integration?

### ISSUE THREAD

**Issue by ifeltsweet** [duffelhq/duffel-components#302]
We use Sentry to monitor errors in our application, however Duffel components also include Sentry which integrates with Duffel's Sentry account. This creates a bunch of different issues for us, including Sentry version incompatibilities.

I imagine a reusable library like this should not hardcode Duffel's Sentry integration for other apps to use. If it does it should make this integration optional and create a separate Sentry instance for itself - https://docs.sentry.io/platforms/javascript/best-practices/multiple-sentry-instances/

**Comment by andrejak** [comment]
Hi! We use Sentry to help us improve the components, as we get alerts about issues that customers are experiencing that way, and can address them proactively. I understand that this can be problematic for you; we'll consider changing that in a future version.
