### ISSUE TITLE
Function not defined 

### ISSUE THREAD

**Issue by devgtt** [duffelhq/duffel-components#313]
Just tried to place this payment component  card , But it gives me error that “the render function is Not defined” 

The payment component code :

https://github.com/duffelhq/duffel-components/blob/main/examples/payments-custom-element/index.html

Please check

**Comment by andrejak** [comment]
Hi @devgtt  , sorry for the delay. Are you still having this issue on the latest version?

**Comment by devgtt** [comment]
Hi

Thanks for reaching out


Yes i need help with implementing it to my website

في اثنين، ٢٥ نوفمبر، ٢٠٢٤ في ٢:٠٥ م، كتب Andreja Kogovsek <
***@***.***>:

**Comment by devgtt** [comment]
Thanks, I'll check it out.

في أربعاء، ٢٧ نوفمبر، ٢٠٢٤ في ١٠:٥٢ ص، كتب Andreja Kogovsek <
***@***.***>:

**Comment by andrejak** [comment]
I'm going to close this for now, feel free to open a new issue if you have problems with the other payment methods.
