### ISSUE TITLE
Missing custom element type files

### ISSUE THREAD

**Issue by jose-seabra** [duffelhq/duffel-components#334]
**Describe the bug**
Installing the newest version of the library doesn't provide multiple *CustomElement.d.ts files.

**Version of @duffel/components**
Using [v3.7.22](https://github.com/duffelhq/duffel-components/releases/tag/v3.7.22)
Installing with npm
Using Vue.js + Vite

**Code sample to reproduce**
Non-applicable

**Expected behavior**
Installing the library should provide all *CustomElement.d.ts files

**Screenshots**
![image](https://github.com/user-attachments/assets/8bfb7d80-1e0d-487b-9521-ccbee9ccbaf9)
![image](https://github.com/user-attachments/assets/7ffab179-a5d6-4c55-9fda-0e13c69b27fb)

**Comment by andrejak** [comment]
Hi @jose-seabra , are you still having this issue with the latest version?

**Comment by jose-seabra** [comment]
hi @andrejak, it's no longer an issue.
Thanks
